MERGE INTO COFFEE AS T USING (
    SELECT 'Coffee arabica' AS COFFEE, 39.9 AS PRICE
    UNION
    SELECT 'Civets feces coffee' AS COFFEE, 1203.9 AS PRICE
    UNION
    SELECT 'Coffee caniphora' AS COFFEE, 32 AS PRICE
    UNION
    SELECT 'Coffee Excelsa' AS COFFEE, 28.7 AS PRICE
    UNION
    SELECT 'Coffee Liberica' AS COFFEE, 34.2 AS PRICE
    ) AS S ON T.COFFEE = S.COFFEE
    WHEN NOT MATCHED THEN
INSERT
    (COFFEE, PRICE)
VALUES (S.COFFEE, S.PRICE);